website/__init__.py
from flask import Flask


def create_app():
    app = Flask(__name__)
    app.secret_key = 'GOLDSHIRE'

    from .routes import db_edit

    app.register_blueprint(db_edit, url_prefix='/db')
    return app

website/routes.py
from flask import Blueprint,render_template, request, url_for, flash, jsonify
from . import Forms
from . import Database

db_edit = Blueprint('db_edit', __name__)

cat_to_type = {
    'Рабочая станция оператора': ['Компьютер', 'Звуковая система'],
    'Видеооборудование': ['Камера'],
    'Аудиооборудование': ['Микрофон', 'Колонки'],
    'Фурнитура': ['Стулья', 'Столы']
}

""" type_to_name = {
    'Компьютер': ['n1', 'n2'],
    'Звуковая система': ['n3', 'n4'],
    'Камера': ['n5', 'n6'],
    'Микрофон': ['n7', 'n8'],
    'Колонки': ['n9', 'n10'],
    'Стулья': ['n11', 'n12'],
    'Столы': ['n13', 'n14']
} """

@db_edit.route('/', methods=['GET', 'POST'])

def add_to_db_form():

    add_to_db_form = Forms.AddToDBForm()
    add_to_db_form.type.choices = cat_to_type['Рабочая станция оператора']
    """ add_to_db_form.name.choices = type_to_name['Компьютер'] """

    if add_to_db_form.validate_on_submit():

        category = add_to_db_form.category.data
        type = add_to_db_form.type.data
        name = add_to_db_form.name.data
        description = add_to_db_form.description.data
        description2 = add_to_db_form.description2.data

        print(description)

        Database.append_database(category, type, name, description, description2)

        flash('Устройство добавлено', category='ok')

    else:
        flash("""Пояснение:
        Категория - имеется в виду к чему относится устройство (прим. видеокарта относится к компу)
        Тип - тип устройства (прим.: видеокарта, стойка, камера и т.д.
        Наименование - полное название устройства как их писал разработчик
        Описание - просто вставляешь текст из ТЗ""")




    return render_template('database_edit.html', add_to_db_form=add_to_db_form)

@db_edit.route('/type/<category>')

def get_type(category):
    types_names = cat_to_type[category]                     # создаем список с типами относящимися к данной категории
                                                            # (сейчас через временный список сверху, позже - со специальной ДБ)
    types = [{'name': name} for name in types_names]        # приводим список с типами в формат JSON
    return jsonify({'types': types})


""" 
@db_edit.route('/type/name/<type>')
def get_name(type):
    name_names = type_to_name[type]                         # создаем список с именами относящимися к данному типу
                                                            # (сейчас через временный список сверху, позже - со специальной ДБ)
    names = [{'name': name} for name in name_names]        # приводим список с именами в формат JSON
    return jsonify({'names': names})
 """

website/templates/database_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Редактор</title>
    <!-- <link rel="shortcut icon" href="../static/img/png64/fingerprint.png"> -->
    <link rel="stylesheet" href="../static/css/bootstrap-grid.min.css" >
    <link rel="stylesheet" href="../static/css/bootstrap.min.css" >
    <link rel="stylesheet" href="../static/css/style.css">
     <link rel="stylesheet" href="../static/css/my-style.css" >
    <!-- <link rel="stylesheet" href="../static/awesome-font/css/font-awesome.min.css" > -->
</head>
<body>
  <div class="container">
    <div class="row">
      <h1> Редактор базы данных </h1>


      {% with messages = get_flashed_messages(with_categories=true) %} {% if
         messages %} {% for category, message in messages %} {% if category ==
         'error' %}
         <div class="alert alert-danger alter-dismissable fade show" role="alert">
           {{ message }}
           <button type="button" class="close" data-dismiss="alert">
             <span aria-hidden="true">&times;</span>
           </button>
         </div>
         {% else %}
         <div class="alert alert-success alter-dismissable fade show" role="alert">
           {{ message }}
           <button type="button" class="close" data-dismiss="alert">
             <span aria-hidden="true">&times;</span>
           </button>
         </div>
         {% endif %} {% endfor %} {% endif %} {% endwith %}
     
     
     
     
     <form id="main-form" class="main-form" action="#" method="post">
     
     
         <p> ДОБАВИТЬ ЗАПИСЬ В ДБ</p>
        <form method="post" action="{{ url_for('db_edit.add_to_db_form') }}">
          <div class="row form-row">
            <div class="col">
              {{ add_to_db_form.csrf_token }}
              {{ add_to_db_form.category.label}}
              {{ add_to_db_form.category }}
              {{ add_to_db_form.type.label }}
              {{ add_to_db_form.type }}
              {{ add_to_db_form.name.label }}
              {{ add_to_db_form.name }}
            </div>
          </div>
          <div class="row">
            <div class="col">
              {{ add_to_db_form.description.label }}
              {{ add_to_db_form.description(cols=50, rows=10) }}
            </div>
            <div class="col">
                 {{ add_to_db_form.description2.label }}
              {{ add_to_db_form.description2(cols=50, rows=10) }}
            </div>
          </div>
          <div class="row">
            <div class="col">
              <p><button type="submit"> Добавить запись  </button></p>
            </div>
          </div>
     
     </form>
     
    </div>
  </div>

</body>
</html>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!-- <script src="../static/js/slick.min.js"></script> -->
<!-- <script src="../static/js/main-slick.js"></script> -->
<script>
  let category_select = document.getElementById('category');
  let type_select = document.getElementById('type');
  //let name_select = document.getElementById('name');

/*   function changeName() {

  } */

  category_select.onchange = function(){
    category = category_select.value;

    fetch('/db/type/' + category).then(function(response){
        response.json().then(function(data){
          //console.table(data);
          let optionHTML = '';
          for ( let type of data.types) {
            //alert(type.Камера);
            optionHTML += '<option id="' + type.name + '">' + type. name + "</option>";
          }
          type_select.innerHTML = optionHTML;
        });
    });
  }
</script>